name: CMake
on:
  push:
    branches: master
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  clang:
    runs-on: ubuntu-20.04
    container:
      image: benboeckel/cxx-modules-sandbox:20221109.0
      # Apparently the `checkout` action assumes root access.
      options: --user root
    strategy:
      matrix:
        shared: [ON, OFF]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: configure
        run: /home/modules/misc/root/cmake/bin/cmake -GNinja -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }} -DCMAKE_MAKE_PROGRAM:FILEPATH=/home/modules/misc/root/cmake/bin/ninja -S. -Bbuild
        env:
          CC: /home/modules/misc/root/clang/bin/clang
          CXX: /home/modules/misc/root/clang/bin/clang++
      - name: build
        run: /home/modules/misc/root/cmake/bin/cmake --build build
      - name: test
        run: /home/modules/misc/root/cmake/bin/ctest --test-dir build
  gcc:
    runs-on: ubuntu-20.04
    container:
      image: benboeckel/cxx-modules-sandbox:20221109.0
      # Apparently the `checkout` action assumes root access.
      options: --user root
    strategy:
      matrix:
        shared: [ON, OFF]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: configure
        run: /home/modules/misc/root/cmake/bin/cmake -GNinja -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }} -DCMAKE_MAKE_PROGRAM:FILEPATH=/home/modules/misc/root/cmake/bin/ninja -S. -Bbuild
        env:
          CC: /home/modules/misc/root/gcc/bin/gcc
          CXX: /home/modules/misc/root/gcc/bin/g++
      - name: build
        run: /home/modules/misc/root/cmake/bin/cmake --build build
      - name: test
        run: /home/modules/misc/root/cmake/bin/ctest --test-dir build
  msvc2022:
    runs-on: windows-2022
    strategy:
      matrix:
        shared: [ON, OFF]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: download/cmake
        run: powershell -ExecutionPolicy Bypass -File ${{ github.workspace }}/.github/ci/cmake.ps1
      - name: Visual Studio toolchain environment
        uses: TheMrMilchmann/setup-msvc-dev@v1
        with:
          arch: x64
      - name: configure
        run: ${{ github.workspace }}/.github/cmake/bin/cmake -GNinja -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }} -S. -Bbuild
      - name: build
        run: ${{ github.workspace }}/.github/cmake/bin/cmake --build build
      - name: test
        run: ${{ github.workspace }}/.github/cmake/bin/ctest --test-dir build
